name: Satyam_project

on:
  workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
      AWS_DEFAULT_REGION:
        description: 'AWS Default Region'
        required: true

env:
    TF_VAR_profile: "satyam"
    TF_VAR_ecr_name: "satyam_project"
    TF_VAR_table_name: "employee_infos"
    TF_VAR_api_name: "serverless_demos"
    TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
    AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}

jobs:
    common:
        runs-on: ubuntu-latest
        steps:
            - name: Install Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.7.0

            - name: Install AWS CLI
              run: |
                sudo apt-get update
                sudo apt-get install -y awscli

            - name: Set up environment
              run: bash scripts/aws_configuration.sh          
            

            - name: Terraform init
              run: terraform init

            - name: Terraform Plan
              run: terraform plan