name: Satyam_project

runs:
    using: 'composite'
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
        shell: bash

      
