name: "Ecr image"
description: 'Ecr Repo Check And Image Push Script'
inputs:
  AWS_ACCOUNT_ID:
    description: 'A Github AWS_ACCOUNT_ID'
    required: true
  AWS_PROFILE:
    description: 'A Github AWS_PROFILE'
    required: true
  AWS_DEFAULT_REGION:
    description: 'A Github AWS_DEFAULT_REGION'
    required: true
  GITHUB_COMMIT_HASH:
    description: 'A Github GITHUB_COMMIT_HASH'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check ECR Repository
      id: check-ecr
      run: bash scripts/ecr_repo_check.sh
      shell: bash
            
    - name: Push Image in ECR
      run: bash scripts/image_push_code.sh
      env:
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
          AWS_PROFILE: ${{ inputs.AWS_PROFILE }}
          GITHUB_COMMIT_HASH: ${{ inputs.GITHUB_COMMIT_HASH}}
      shell: bash

