name: Common Terraform Steps

on:
    workflow_call:
env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}

jobs:
  Common_Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up environment
        run: bash scripts/aws_configuration.sh

      - name: Terraform init
        run: terraform init
      
      - name: Terraform preplan
        run: terraform plan
      