name: common configuration
on:
  workflow_call:
    inputs:
      AWS_ACCESS_KEY_ID:
        type: string
        required: true
      AWS_SECRET_ACCESS_KEY:
        type: string
        required: true
      AWS_DEFAULT_REGION:
        type: string
        required: true



env:
  AWS_ACCESS_KEY_ID: ${{inputs.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{inputs.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{inputs.AWS_DEFAULT_REGION}}


  
jobs:
  Configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up environment
        run: bash scripts/aws_configuration.sh          
      

      