name: Satyam_project
'on':
  push:
    branches:
      - devs
  pull_request:
    branches:
      - devs
jobs:

  Devs-PullRequest:
    environment:
      name: devs
    if: github.event.pull_request.base.ref == 'devs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Aws && Terraform Configuration
        uses: ./.github/actions/aws_terraform_configuration
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'

      - name: 'Terraform init, plan and validate'
        uses: ./.github/actions/terraform_init_plan_validate


  Devs-Environment-Deployment:
    if: github.event_name == 'push' && github.ref == 'refs/heads/devs'
    environment:
      name: devs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Aws && Terraform Configuration
        uses: ./.github/actions/aws_terraform_configuration
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          GITHUB_COMMIT_HASH: '${{ github.sha }}'

      - name: Check Repsoitery and Push Image
        uses: ./.github/actions/ECR_push_image
        with:
          AWS_ACCOUNT_ID: ${{ inputs.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ inputs.AWS_DEFAULT_REGION }}
          AWS_PROFILE: ${{ inputs.AWS_PROFILE }}
          GITHUB_COMMIT_HASH: ${{ inputs.GITHUB_COMMIT_HASH}}
      
      - name: Terraform init, plan and validate
        uses: ./.github/actions/terraform_init_plan_validate
      
      - name: Terraform Apply
        run: terraform apply