name: Satyam_project
'on':
  push:
    branches:
      - devs
  pull_request:
    branches:
      - devs
      
env:
  TF_VAR_api_name : "EmployeeInfo_devs"
  TF_VAR_table_name : "employee_infos_devs"
  TF_VAR_ecr_name : "project_devs"
  TF_VAR_function_name : "lambda_function_devs"
  TF_VAR_iam_role_name : "lambda_execution_role_devs"
  TF_VAR_ecr_access_policy : "ecr_access_policy_devs"
  TF_VAR_dyanmodb_access_policy : "DynamoDb_access_policy_devs"
  TF_VAR_cloudwatch_access_policy : "cloudwatch_logs_policy_devs"


jobs:
  Enviroment:
      runs-on: ubuntu-latest
      outputs:
        current_env: ${{ steps.set_env.outputs.my_var }}
      steps:
        - name: Set output
          id: set_env
          run: |
            echo "my_var=devs" >> $GITHUB_OUTPUT

  
  Devs-PullRequest:
    needs: Enviroment
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.Enviroment.outputs.current_env }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Aws && Terraform Configuration
        uses: ./.github/actions/aws_terraform_configuration
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace
        run: terraform workspace select devs

      - name: 'Terraform init, plan and validate'
        uses: ./.github/actions/terraform_plan_validate



  Devs-Environment-Deployment:
    needs: Enviroment
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.Enviroment.outputs.current_env }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Aws && Terraform Configuration
        uses: ./.github/actions/aws_terraform_configuration
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          GITHUB_COMMIT_HASH: '${{ github.sha }}'
      
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Workspace
        run: terraform workspace select devs
      
      - name: Check Repsoitery and Push Image
        uses: ./.github/actions/ECR_push_image_Devs
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          GITHUB_COMMIT_HASH: '${{ github.sha }}'
      
      - name: Terraform init, plan and validate
        uses: ./.github/actions/terraform_plan_validate
      
      - name: Terraform Apply
        run: terraform apply -auto-approve 

