name: Satyam_project

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - master

env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  terraform-and-build:  # Combined job for Terraform and build
    runs-on: ubuntu-latest  # Use ARM64 runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up environment
        run: |
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_DEFAULT_REGION }}"
      
      - name: Configuration
        run: bash scripts/aws_configuration.sh

      # - name: Terraform init
      #   run: terraform init

      # - name: Terraform preplan
      #   run: terraform plan
      
      # - name: Run Shell Script
      #   run: bash scripts/run_command.sh
  
      # - name: Terraform apply plan
      #   run: terraform apply -auto-approve

      


      