name: Satyam_project

on:
  push:
    branches:
      - master

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: Configure AWS Credentials
        run: |
          aws configure --profile satyam set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure --profile satyam set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure --profile satyam set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          
      - name: Check AWS Account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
          echo "Current AWS Account ID: $ACCOUNT_ID"
      

      
      