name: Satyam_project

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  terraform-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up environment
        run: bash scripts/aws_configuration.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
      
      - name: Terraform init
        run: terraform init

      - name: Terraform preplan
        run: terraform plan
      

      - name: Check ECR Repository
        id: check-ecr
        run: |
          if aws ecr describe-repositories --repository-names "satyam_project" --profile satyam &> /dev/null; then
              echo "ECR repository exists"
              echo "::set-output name=exists::true"
          else
              echo "::set-output name=exists::false"
          fi

      
      - name: Terraform Apply
        run: |
          if [ "${{ steps.check-ecr.outputs.exists }}" == 'true' ]; then
              bash scripts/run_command.sh
          else
              terraform apply -auto-approve 
          fi



      # - name: Terraform apply plan
      #   run: terraform apply -auto-approve

      # - name: Run Shell Script

      


      