name: Satyam_project

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master
    
env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
  GITHUB_COMMIT_HASH: ${{ github.sha }}
  


  
jobs:
  terraform-and-build:
    environment:
      name: dev
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configuration Terraform and AWS 
        uses: ./.github/actions/common_configure
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_PROFILE: ${{secrets.AWS_PROFILE}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Validate
        run: terraform validate
  



        
  terraform-apply-final:
      if: github.event_name == 'push'
      environment:
        name: stage
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Configuration Terraform and AWS 
          uses: ./.github/actions/common_configure
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
        - name: Terraform Init
          run: terraform init
  
        - name: ECR Image Push
          uses: ./.github/actions/ECR_push_image
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            GITHUB_COMMIT_HASH: ${{ github.sha }}
  
        - name: Terraform Plan
          run: terraform plan
        
        - name: Terraform Validate
          run: terraform validate
    
        - name: Terraform Apply
          run: terraform apply -auto-approve



