name: Satyam_project

on:
  push:
    branches:
      - dev
      
  pull_request:
    branches:
      - master
    
env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}


  
jobs:
  terraform-and-build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Common Config
        uses: satyamdudhat/satyam-terra-project/.github/actions/common_config.yml
        with:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      



        

  