name: Satyam_project

on:
  push:
    branches:
      - master
      - dev
      
  pull_request:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}
      

jobs:
  terraform-and-build:
    if: github.event_name == 'push'
    uses: ./.github/workflows/common_terraform_steps.yml

  