name: Satyam_project

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master
    
env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}
  


  
jobs:
  terraform-and-build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: common configuration
        uses: ./actions/common_configure

      - name: Set up aws configuration
        run: bash scripts/aws_configuration.sh          
      
      - name: Terraform INIT
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
  



        
  terraform-apply-final:
      if: github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: common configuration
          uses: ./actions/common_configure
  

        - name: Set up aws configuration
          run: bash scripts/aws_configuration.sh


        - name: Terraform INIT
          run: terraform init
  
        - name: Terraform Plan
          run: terraform plan
    
  
        - name: Check ECR Repository
          id: check-ecr
          run: bash scripts/ecr_repo_check.sh
            
        - name: Push Image in ECR
          run: bash scripts/image_push_code.sh


        - name: Terraform Apply
          run: terraform apply -auto-approve



