name: Satyam_project

on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - master

env:
  TF_VAR_profile: "satyam"
  TF_VAR_ecr_name: "satyam_project"
  TF_VAR_table_name: "employee_infos"
  TF_VAR_api_name: "serverless_demos"
  TF_VAR_accountId: ${{ secrets.AWS_ACCOUNT_ID }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64, linux/arm]


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          platforms: arm,arm64

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configuration
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile satyam
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile satyam
          aws configure set region ${{ secrets.AWS_DEFAULT_REGION }} --profile satyam
      
      - name: Building Docker Image and push
        run: >
          aws ecr get-login-password --region ap-south-1 --profile satyam | docker login --username AWS --password-stdin 637423557273.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t satyam_project:latest --platform=${{ matrix.platform }} .
          docker tag satyam_project:latest 637423557273.dkr.ecr.ap-south-1.amazonaws.com/satyam_project:latest
          docker push 637423557273.dkr.ecr.ap-south-1.amazonaws.com/satyam_project:latest
        
      
      - name: Terraform init
        run: terraform init

      - name: Terraform destroy (if applicable)
        run: terraform destroy -auto-approve  # Optional: Only run if necessary

      - name: Terraform preplan
        run: terraform plan

      - name: Terraform apply plan
        run: terraform apply -auto-approve
