name: Final_project
on:
  push:
    branches: master
    
# env:
#   profile: "sandbox"
#   ecr_name: "satyam_project"
#   table_name: "employee_infos"
#   api_name: "serverless_demos"
#   accountId: "843728461002"
  



  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
         
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.3.0
         
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          cli_follow_urlparam: true # This parameter is not needed, but you can specify it if required.
          sso_start_url: ${{ secrets.AWS_SSO_START_URL }}
          sso_region: ${{ secrets.AWS_REGION }}
          sso_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          sso_role_name: ${{ secrets.AWS_ROLE_NAME }}
          
      - name: Check AWS Account
        run: |
          aws --version
          
          # List S3 buckets to verify AWS CLI connectivity
          aws s3 ls
