name: Satyam_project

on:
  push:
    branches:
      - master
      
  pull_request:
    branches:
      - master

jobs:
  terraform-and-build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/common_terraform_steps.yml

