name: Satyam_project

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}


jobs:
  terraform-and-build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: ../setup_and_terraform.yml@v1

      - name: Check ECR Repository
        id: check-ecr
        run: bash scripts/ecr_repo_check.sh
    
      - name: Push Image in ECR
        run: bash scripts/image_push_code.sh


  terraform-apply-final:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: ./setup_and_terraform.yml@v1

      - name: Terraform Apply
        run: terraform apply -auto-approve
