name: Satyam_project

on:
  push:
    branches:
      - master
      - dev
      
  pull_request:
    branches:
      - master


env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
  AWS_PROFILE: ${{secrets.AWS_PROFILE}}
      

jobs:
  terraform-and-build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/common_terraform_steps.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}



  terraform-apply-final:
      if: github.event_name == 'push'
      runs-on: ubuntu-latest
      steps:
        - name: Configuration
          uses: satyam-terra-project/.github/workflows/common_terraform_steps.yml

        - name: Check ECR Repository
          id: check-ecr
          run: bash scripts/ecr_repo_check.sh
            
        
        - name: Push Image in ECR
          run: bash scripts/image_push_code.sh


        - name: Terraform Apply
          run: terraform apply -auto-approve



  