name: Satyam_project

on:
  push:
    branches:
      - devs
      - stage
      - master

  pull_request:
    branches:
      - devs
      - stage
      - master
    
jobs:
  terraform-and-build:
    environment:
      name: 'master'
    if: github.event_name == 'pull_request' 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configuration Terraform and AWS 
        uses: ./.github/actions/common_configure
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_PROFILE: ${{secrets.AWS_PROFILE}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Validate
        run: terraform validate
  


        
        
  terraform-apply-final:
      if: github.event_name == 'push'  && github.ref == 'refs/heads/devs'
      environment:
        name: 'devs'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Configuration Terraform and AWS 
          uses: ./.github/actions/common_configure
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
        - name: Terraform Init
          run: terraform init
  
        - name: ECR Image Push
          uses: ./.github/actions/ECR_push_image
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            GITHUB_COMMIT_HASH: ${{ github.sha }}
  
        - name: Terraform Plan
          run: terraform plan
        
        - name: Terraform Validate
          run: terraform validate
    
        - name: Terraform Apply
          run: terraform apply -auto-approve



