name: Satyam_project

on:
  push:
    branches:
      - devs
      - stage
      - master

  pull_request:
    branches:
      - devs
      - stage
      - master
    
jobs:
  Master-PullRequest:
    environment:
      name: 'master'
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configuration Terraform and AWS 
        uses: ./.github/actions/common_configure
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_PROFILE: ${{secrets.AWS_PROFILE}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      

  Devs-PullRequest:
    environment:
      name: 'devs'
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/devs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configuration Terraform and AWS 
        uses: ./.github/actions/common_configure
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_PROFILE: ${{secrets.AWS_PROFILE}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  

  Stage-PullRequest:
    environment:
      name: 'stage'
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configuration Terraform and AWS 
        uses: ./.github/actions/common_configure
        with:
          AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
          AWS_PROFILE: ${{secrets.AWS_PROFILE}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      
  




  Master-Environment:
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      environment: 
        name: 'master'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Common Steps 
          uses: ./.github/actions/common_workflow_enviroments
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            GITHUB_COMMIT_HASH: ${{ github.sha }}

        
        
  Dev-Environment:
      if: github.event_name == 'push'  && github.ref == 'refs/heads/devs'
      environment:
        name: devs
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Common Steps 
          uses: ./.github/actions/common_workflow_enviroments
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            GITHUB_COMMIT_HASH: ${{ github.sha }}



  Stage-Environment:
      if: github.event_name == 'push' && github.ref == 'refs/heads/stage'
      environment: 
        name: 'stage'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Common Steps 
          uses: ./.github/actions/common_workflow_enviroments
          with:
            AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
            AWS_PROFILE: ${{secrets.AWS_PROFILE}}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
            GITHUB_COMMIT_HASH: ${{ github.sha }}


  