name: Final_project
on:
  push:
    branches: master
    
# env:
#   profile: "sandbox"
#   ecr_name: "satyam_project"
#   table_name: "employee_infos"
#   api_name: "serverless_demos"
#   accountId: "843728461002"
  



  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
         
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
         terraform_version: 1.3.0
         
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          sso-start-url: ${{ secrets.AWS_SSO_START_URL }}
          sso-region: ${{ secrets.AWS_REGION }}
          sso-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
          sso-role-name: ${{ secrets.AWS_ROLE_NAME }}
          sso-role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          
      - name: Check AWS Account
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
          echo "Current AWS Account ID: $ACCOUNT_ID"
