name: Satyam_project
'on':
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:

  Stage-PullRequest:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Aws && Terraform Configuration
        uses: ./.github/actions/aws_terraform_configuration
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'

      - name: 'Terraform init, plan and validate'
        uses: ./.github/actions/terraform_init_plan_validate


  Stage-Environment-Deployment:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
     

      - name: Aws && Terraform Configuration
        uses: ./.github/actions/aws_terraform_configuration
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          GITHUB_COMMIT_HASH: '${{ github.sha }}'

      - name: Check Repsoitery and Push Image
        uses: ./.github/actions/ECR_push_image
        with:
          AWS_ACCOUNT_ID: '${{secrets.AWS_ACCOUNT_ID}}'
          AWS_DEFAULT_REGION: '${{ secrets.AWS_DEFAULT_REGION }}'
          AWS_PROFILE: '${{secrets.AWS_PROFILE}}'
          GITHUB_COMMIT_HASH: '${{ github.sha }}'
      
      - name: Terraform init, plan and validate
        uses: ./.github/actions/terraform_init_plan_validate
      
      - name: Terraform Apply
        run: terraform apply -auto-approve